project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1a
            href: Hands-on_Ex/Hands-on_Ex1/hands-on_ex1a.qmd
          - text: Hands-on Exercise 1b
            href: Hands-on_Ex/Hands-on_Ex1/hands-on_ex1b.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex/Hands-on_Ex2/hands-on_ex2.qmd
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/in-class_ex1.qmd
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            href: Take-home_Ex/Take-home_Ex1/take-home_ex1.qmd
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

