<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lee Chee Tian">

<title>ISSS624 - Take-home Exercise 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS624</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex1/hands-on_ex1a.html">
 <span class="dropdown-text">Hands-on Exercise 1a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex1/hands-on_ex1b.html">
 <span class="dropdown-text">Hands-on Exercise 1b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex2/hands-on_ex2.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex3/hands-on_ex3.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex1/in-class_ex1.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex2/in-class_ex2.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex1/take-home_ex1.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#geospatial-analytics-for-social-good" id="toc-geospatial-analytics-for-social-good" class="nav-link active" data-scroll-target="#geospatial-analytics-for-social-good">Geospatial Analytics for Social Good</a>
  <ul class="collapse">
  <li><a href="#objective" id="toc-objective" class="nav-link" data-scroll-target="#objective">Objective</a></li>
  <li><a href="#loading-r-packages" id="toc-loading-r-packages" class="nav-link" data-scroll-target="#loading-r-packages">Loading R Packages</a></li>
  <li><a href="#importing-data-into-r" id="toc-importing-data-into-r" class="nav-link" data-scroll-target="#importing-data-into-r">Importing Data into R</a>
  <ul class="collapse">
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#importing-nigeria-shapefile" id="toc-importing-nigeria-shapefile" class="nav-link" data-scroll-target="#importing-nigeria-shapefile">Importing Nigeria Shapefile</a></li>
  <li><a href="#importing-water-points-aspatial-data" id="toc-importing-water-points-aspatial-data" class="nav-link" data-scroll-target="#importing-water-points-aspatial-data">Importing Water Points Aspatial Data</a></li>
  </ul></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#recoding-na-values-into-string" id="toc-recoding-na-values-into-string" class="nav-link" data-scroll-target="#recoding-na-values-into-string">Recoding NA values into string</a></li>
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda">EDA</a></li>
  </ul></li>
  <li><a href="#extracting-water-points-data" id="toc-extracting-water-points-data" class="nav-link" data-scroll-target="#extracting-water-points-data">Extracting Water Points Data</a>
  <ul class="collapse">
  <li><a href="#extracting-functional-water-points" id="toc-extracting-functional-water-points" class="nav-link" data-scroll-target="#extracting-functional-water-points">Extracting functional water points</a></li>
  <li><a href="#extracting-non-functional-water-points" id="toc-extracting-non-functional-water-points" class="nav-link" data-scroll-target="#extracting-non-functional-water-points">Extracting non-functional water points</a></li>
  <li><a href="#extracting-water-points-with-unknown-class" id="toc-extracting-water-points-with-unknown-class" class="nav-link" data-scroll-target="#extracting-water-points-with-unknown-class">Extracting water points with Unknown class</a></li>
  </ul></li>
  <li><a href="#performing-point-in-polygon-count" id="toc-performing-point-in-polygon-count" class="nav-link" data-scroll-target="#performing-point-in-polygon-count">Performing Point-in-Polygon Count</a></li>
  <li><a href="#saving-the-analytical-data-table" id="toc-saving-the-analytical-data-table" class="nav-link" data-scroll-target="#saving-the-analytical-data-table">Saving the Analytical Data Table</a></li>
  <li><a href="#visualizing-the-spatial-distribution-of-water-points" id="toc-visualizing-the-spatial-distribution-of-water-points" class="nav-link" data-scroll-target="#visualizing-the-spatial-distribution-of-water-points">Visualizing the Spatial Distribution of Water Points</a></li>
  <li><a href="#computing-distance-based-neighbours" id="toc-computing-distance-based-neighbours" class="nav-link" data-scroll-target="#computing-distance-based-neighbours">Computing Distance-Based Neighbours</a>
  <ul class="collapse">
  <li><a href="#finding-coordinates-of-lga-polygon-centroids" id="toc-finding-coordinates-of-lga-polygon-centroids" class="nav-link" data-scroll-target="#finding-coordinates-of-lga-polygon-centroids">Finding Coordinates of LGA Polygon Centroids</a></li>
  <li><a href="#computing-adaptive-distance-weight-matrix" id="toc-computing-adaptive-distance-weight-matrix" class="nav-link" data-scroll-target="#computing-adaptive-distance-weight-matrix">Computing Adaptive Distance Weight Matrix</a></li>
  </ul></li>
  <li><a href="#computing-spatially-lagged-values-of-lgas" id="toc-computing-spatially-lagged-values-of-lgas" class="nav-link" data-scroll-target="#computing-spatially-lagged-values-of-lgas">Computing Spatially Lagged Values of LGAs</a></li>
  <li><a href="#cluster-and-outlier-analysis" id="toc-cluster-and-outlier-analysis" class="nav-link" data-scroll-target="#cluster-and-outlier-analysis">Cluster and Outlier Analysis</a>
  <ul class="collapse">
  <li><a href="#global-spatial-autocorrelation-morans-i-test" id="toc-global-spatial-autocorrelation-morans-i-test" class="nav-link" data-scroll-target="#global-spatial-autocorrelation-morans-i-test">Global Spatial Autocorrelation: Moran’s I test</a></li>
  <li><a href="#computing-local-morans-i" id="toc-computing-local-morans-i" class="nav-link" data-scroll-target="#computing-local-morans-i">Computing Local Moran’s I</a></li>
  </ul></li>
  <li><a href="#creating-lisa-cluster-map" id="toc-creating-lisa-cluster-map" class="nav-link" data-scroll-target="#creating-lisa-cluster-map">Creating LISA Cluster Map</a>
  <ul class="collapse">
  <li><a href="#plotting-moran-scatterplot" id="toc-plotting-moran-scatterplot" class="nav-link" data-scroll-target="#plotting-moran-scatterplot">Plotting Moran Scatterplot</a></li>
  <li><a href="#plotting-moran-scatterplot-with-standardized-variable" id="toc-plotting-moran-scatterplot-with-standardized-variable" class="nav-link" data-scroll-target="#plotting-moran-scatterplot-with-standardized-variable">Plotting Moran Scatterplot with Standardized Variable</a></li>
  <li><a href="#preparing-lisa-map-classes" id="toc-preparing-lisa-map-classes" class="nav-link" data-scroll-target="#preparing-lisa-map-classes">Preparing LISA Map Classes</a></li>
  <li><a href="#plotting-lisa-map" id="toc-plotting-lisa-map" class="nav-link" data-scroll-target="#plotting-lisa-map">Plotting LISA Map</a></li>
  </ul></li>
  <li><a href="#hot-spot-and-cold-spot-area-analysis" id="toc-hot-spot-and-cold-spot-area-analysis" class="nav-link" data-scroll-target="#hot-spot-and-cold-spot-area-analysis">Hot Spot and Cold Spot Area Analysis</a>
  <ul class="collapse">
  <li><a href="#computing-adaptive-distance-weight-matrix-1" id="toc-computing-adaptive-distance-weight-matrix-1" class="nav-link" data-scroll-target="#computing-adaptive-distance-weight-matrix-1">Computing Adaptive Distance Weight Matrix</a></li>
  <li><a href="#computing-gi-statistics" id="toc-computing-gi-statistics" class="nav-link" data-scroll-target="#computing-gi-statistics">Computing Gi Statistics</a></li>
  <li><a href="#mapping-gi-values-with-adaptive-distance-weights" id="toc-mapping-gi-values-with-adaptive-distance-weights" class="nav-link" data-scroll-target="#mapping-gi-values-with-adaptive-distance-weights">Mapping Gi Values with Adaptive Distance Weights</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lee Chee Tian </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="geospatial-analytics-for-social-good" class="level1">
<h1>Geospatial Analytics for Social Good</h1>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">Objective</h2>
<p>To reveal the geospatial patterns of Functional and Non-functional water points in Nigeria using global and local spatial association techniques.</p>
</section>
<section id="loading-r-packages" class="level2">
<h2 class="anchored" data-anchor-id="loading-r-packages">Loading R Packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spdep, tmap, tidyverse, funModeling)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-data-into-r" class="level2">
<h2 class="anchored" data-anchor-id="importing-data-into-r">Importing Data into R</h2>
<section id="the-data" class="level3">
<h3 class="anchored" data-anchor-id="the-data">The Data</h3>
<p>ESRI shapefile data of Nigeria showing Level-2 Administrative (or Local Government Area, LGA) boundary was obtained from geoBoundaries:</p>
<p><img src="nigeria adm2 geospatial data.jpg" class="img-fluid"></p>
<p>Water point data in CSV format was obtained from WPdx data repository:</p>
<p><img src="nigeria aspatial data.jpg" class="img-fluid"></p>
<p>As the size of the CSV file has exceeded the GitHub limitation of 100 MB, it shall not be included in the Commit and Push to GitHub and Netlify. The wrangled data derived from the following steps for the subsequent geospatial analysis will be exported as a RDS file, and this will be pushed to GitHub and Netlify instead.</p>
</section>
<section id="importing-nigeria-shapefile" class="level3">
<h3 class="anchored" data-anchor-id="importing-nigeria-shapefile">Importing Nigeria Shapefile</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>nigeria_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn=</span><span class="st">"data/Nigeria"</span>, <span class="at">layer=</span><span class="st">"geoBoundaries-NGA-ADM2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geoBoundaries-NGA-ADM2' from data source 
  `D:\SMU\ISSS624 - Applied Geospatial Analytics\exercises\leecheetian\ISSS624\Take-home_Ex\Take-home_Ex1\data\Nigeria' 
  using driver `ESRI Shapefile'
Simple feature collection with 774 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2.668534 ymin: 4.273007 xmax: 14.67882 ymax: 13.89442
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nigeria_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="take-home_ex1_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(nigeria_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 774
Columns: 6
$ shapeName  &lt;chr&gt; "Aba North", "Aba South", "Abadam", "Abaji", "Abak", "Abaka…
$ Level      &lt;chr&gt; "ADM2", "ADM2", "ADM2", "ADM2", "ADM2", "ADM2", "ADM2", "AD…
$ shapeID    &lt;chr&gt; "NGA-ADM2-72505758B79815894", "NGA-ADM2-72505758B67905963",…
$ shapeGroup &lt;chr&gt; "NGA", "NGA", "NGA", "NGA", "NGA", "NGA", "NGA", "NGA", "NG…
$ shapeType  &lt;chr&gt; "ADM2", "ADM2", "ADM2", "ADM2", "ADM2", "ADM2", "ADM2", "AD…
$ geometry   &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((7.401109 5...., MULTIPOLYGON (…</code></pre>
</div>
</div>
<section id="transforming-to-epsg-26393-map-projection" class="level4">
<h4 class="anchored" data-anchor-id="transforming-to-epsg-26393-map-projection">Transforming to EPSG 26393 Map Projection</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>nigeria26393 <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(nigeria_sf, <span class="at">crs =</span> <span class="dv">26393</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>nigeria26393</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 774 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 21379.36 ymin: 33072.08 xmax: 1347569 ymax: 1105146
Projected CRS: Minna / Nigeria East Belt
First 10 features:
        shapeName Level                    shapeID shapeGroup shapeType
1       Aba North  ADM2 NGA-ADM2-72505758B79815894        NGA      ADM2
2       Aba South  ADM2 NGA-ADM2-72505758B67905963        NGA      ADM2
3          Abadam  ADM2 NGA-ADM2-72505758B57073987        NGA      ADM2
4           Abaji  ADM2 NGA-ADM2-72505758B61968000        NGA      ADM2
5            Abak  ADM2 NGA-ADM2-72505758B39432389        NGA      ADM2
6       Abakaliki  ADM2 NGA-ADM2-72505758B36739173        NGA      ADM2
7  Abeokuta North  ADM2 NGA-ADM2-72505758B86358915        NGA      ADM2
8  Abeokuta South  ADM2 NGA-ADM2-72505758B56925175        NGA      ADM2
9             Abi  ADM2  NGA-ADM2-72505758B1616690        NGA      ADM2
10    Aboh-Mbaise  ADM2 NGA-ADM2-72505758B78555816        NGA      ADM2
                         geometry
1  MULTIPOLYGON (((544450.6 12...
2  MULTIPOLYGON (((537055.1 12...
3  MULTIPOLYGON (((1254969 104...
4  MULTIPOLYGON (((510382.6 58...
5  MULTIPOLYGON (((590092.2 12...
6  MULTIPOLYGON (((657693.7 25...
7  MULTIPOLYGON (((73280.55 38...
8  MULTIPOLYGON (((90286.32 35...
9  MULTIPOLYGON (((628834.8 21...
10 MULTIPOLYGON (((535932.4 15...</code></pre>
</div>
</div>
</section>
</section>
<section id="importing-water-points-aspatial-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-water-points-aspatial-data">Importing Water Points Aspatial Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>nigeria_csv <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/WPdx+/Water_Point_Data_Exchange_-_Plus__WPdx__.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">#clean_country_name</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Nigeria"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="converting-to-simple-feature-data-frame-and-transforming-to-same-map-projection" class="level4">
<h4 class="anchored" data-anchor-id="converting-to-simple-feature-data-frame-and-transforming-to-same-map-projection">Converting to simple feature data frame and transforming to same map projection</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>nigeria_wp_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(nigeria_csv, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"#lon_deg"</span>, <span class="st">"#lat_deg"</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">26393</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling">Data Wrangling</h2>
<section id="recoding-na-values-into-string" class="level3">
<h3 class="anchored" data-anchor-id="recoding-na-values-into-string">Recoding NA values into string</h3>
<p>Recoding all NA values in <em>#status_clean</em> column into “Unknown”:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>nigeria_wp <span class="ot">&lt;-</span> nigeria_wp_sf <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">replace_na</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span>, <span class="st">"Unknown"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="eda" class="level3">
<h3 class="anchored" data-anchor-id="eda">EDA</h3>
<p>Listing all values in <em>#status_clean</em> column:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data =</span> nigeria_wp, <span class="at">input =</span> <span class="st">"#status_clean"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="extracting-water-points-data" class="level2">
<h2 class="anchored" data-anchor-id="extracting-water-points-data">Extracting Water Points Data</h2>
<section id="extracting-functional-water-points" class="level3">
<h3 class="anchored" data-anchor-id="extracting-functional-water-points">Extracting functional water points</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>wp_functional <span class="ot">&lt;-</span> nigeria_wp <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Functional"</span>, </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Functional but needs repair"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Functional but not in use"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-non-functional-water-points" class="level3">
<h3 class="anchored" data-anchor-id="extracting-non-functional-water-points">Extracting non-functional water points</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>wp_nonfunctional <span class="ot">&lt;-</span> nigeria_wp <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Non-Functional"</span>, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Non-Functional due to dry season"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Non functional due to dry season"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Abandoned/Decommissioned"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Abandoned"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-water-points-with-unknown-class" class="level3">
<h3 class="anchored" data-anchor-id="extracting-water-points-with-unknown-class">Extracting water points with Unknown class</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>wp_unknown <span class="ot">&lt;-</span> nigeria_wp <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">#status_clean</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Unknown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="performing-point-in-polygon-count" class="level2">
<h2 class="anchored" data-anchor-id="performing-point-in-polygon-count">Performing Point-in-Polygon Count</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>wp_nigeria <span class="ot">&lt;-</span> nigeria26393 <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Total water points</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersects</span>(nigeria26393, nigeria_wp))) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Functional status</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersects</span>(nigeria26393, wp_functional))) <span class="sc">%&gt;%</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Non-functional status</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersects</span>(nigeria26393, wp_nonfunctional))) <span class="sc">%&gt;%</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Unknown status</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersects</span>(nigeria26393, wp_unknown))) <span class="sc">%&gt;%</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Functional %</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ifelse</span>(<span class="st">`</span><span class="at">Total water points</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">0</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">`</span><span class="at">Functional status</span><span class="st">`</span> <span class="sc">/</span> <span class="st">`</span><span class="at">Total water points</span><span class="st">`</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>                                 <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Non-functional %</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ifelse</span>(<span class="st">`</span><span class="at">Total water points</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">0</span>,</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Non-functional status</span><span class="st">`</span> <span class="sc">/</span> <span class="st">`</span><span class="at">Total water points</span><span class="st">`</span>, <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>wp_nigeria</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="saving-the-analytical-data-table" class="level2">
<h2 class="anchored" data-anchor-id="saving-the-analytical-data-table">Saving the Analytical Data Table</h2>
<p>The data derived above is saved as a RDS file for subsequent geospatial analysis of the water points:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(wp_nigeria, <span class="st">"data/rds/wp_nigeria.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualizing-the-spatial-distribution-of-water-points" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-spatial-distribution-of-water-points">Visualizing the Spatial Distribution of Water Points</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>wp_nigeria <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/wp_nigeria.rds"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">qtm</span>(wp_nigeria, <span class="st">"Total water points"</span>, <span class="at">fill.palette =</span> <span class="st">"Purples"</span>) <span class="sc">+</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Total Water Points"</span>, </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>wp_functional <span class="ot">&lt;-</span> <span class="fu">qtm</span>(wp_nigeria, <span class="st">"Functional status"</span>, <span class="at">fill.palette =</span> <span class="st">"Blues"</span>) <span class="sc">+</span> </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Functional Water Points"</span>, </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>wp_nonfunctional <span class="ot">&lt;-</span> <span class="fu">qtm</span>(wp_nigeria, <span class="st">"Non-functional status"</span>, <span class="at">fill.palette =</span> <span class="st">"Oranges"</span>) <span class="sc">+</span> </span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Non-functional Water Points"</span>, </span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>,</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>unknown <span class="ot">&lt;-</span> <span class="fu">qtm</span>(wp_nigeria, <span class="st">"Unknown status"</span>, <span class="at">fill.palette =</span> <span class="st">"Greys"</span>) <span class="sc">+</span> </span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Water Points with Unknown Status"</span>, </span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.0</span>,</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>pct_functional <span class="ot">&lt;-</span> <span class="fu">qtm</span>(wp_nigeria, <span class="st">"Functional %"</span>, <span class="at">fill.palette =</span> <span class="st">"Blues"</span>) <span class="sc">+</span> </span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"% Functional Water Points"</span>, </span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>,</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>, </span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.format =</span> <span class="fu">list</span>(<span class="at">fun=</span><span class="cf">function</span>(x) <span class="fu">paste0</span>(<span class="fu">formatC</span>(x <span class="sc">*</span> <span class="dv">100</span>, <span class="at">digits=</span><span class="dv">0</span>, <span class="at">format=</span><span class="st">"f"</span>), <span class="st">" %"</span>)))</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>pct_nonfunctional <span class="ot">&lt;-</span> <span class="fu">qtm</span>(wp_nigeria, <span class="st">"Non-functional %"</span>, <span class="at">fill.palette =</span> <span class="st">"Oranges"</span>) <span class="sc">+</span> </span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"% Non-functional Water Points"</span>, </span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>,</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>, </span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.format =</span> <span class="fu">list</span>(<span class="at">fun=</span><span class="cf">function</span>(x) <span class="fu">paste0</span>(<span class="fu">formatC</span>(x <span class="sc">*</span> <span class="dv">100</span>, <span class="at">digits=</span><span class="dv">0</span>, <span class="at">format=</span><span class="st">"f"</span>), <span class="st">" %"</span>)))</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(total, wp_functional, wp_nonfunctional, unknown, pct_functional, pct_nonfunctional, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Some legend labels were too wide. These labels have been resized to 0.64, 0.64, 0.64, 0.58. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.
Some legend labels were too wide. These labels have been resized to 0.64, 0.64, 0.64, 0.58. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="take-home_ex1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the above maps, it appears that the northern regions of Nigeria tend to enjoy both a higher count as well as percentage of functional water points, while the central and southern regions suffer a higher count and percentage of non-functional ones.</p>
</section>
<section id="computing-distance-based-neighbours" class="level2">
<h2 class="anchored" data-anchor-id="computing-distance-based-neighbours">Computing Distance-Based Neighbours</h2>
<section id="finding-coordinates-of-lga-polygon-centroids" class="level3">
<h3 class="anchored" data-anchor-id="finding-coordinates-of-lga-polygon-centroids">Finding Coordinates of LGA Polygon Centroids</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>longitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(wp_nigeria<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">1</span>]])</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>latitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(wp_nigeria<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">2</span>]])</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(longitude, latitude)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     longitude  latitude
[1,]  541288.4  125251.5
[2,]  539000.4  121951.9
[3,] 1199527.8 1042662.8
[4,]  487780.1  538172.6
[5,]  585617.2  114810.5
[6,]  636457.5  251692.0</code></pre>
</div>
</div>
</section>
<section id="computing-adaptive-distance-weight-matrix" class="level3">
<h3 class="anchored" data-anchor-id="computing-adaptive-distance-weight-matrix">Computing Adaptive Distance Weight Matrix</h3>
<p>We set k-nearest neighbours to 8 to find the 8 nearest neighbours of each LGA using adaptive distance method:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>knn <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k =</span> <span class="dv">8</span>))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>knn</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 774 
Number of nonzero links: 6192 
Percentage nonzero weights: 1.033592 
Average number of links: 8 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<section id="inversed-distance-weight-matrix" class="level4">
<h4 class="anchored" data-anchor-id="inversed-distance-weight-matrix">Inversed Distance Weight Matrix</h4>
<p>Deriving a spatial weight matrix based on Inversed Distance method:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> <span class="fu">nbdists</span>(knn, coords)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>ids <span class="ot">&lt;-</span> <span class="fu">lapply</span>(dist, <span class="cf">function</span>(x) <span class="dv">1</span><span class="sc">/</span>(x<span class="sc">/</span><span class="dv">1000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The distance is divided by 1000 to obtain the value in km.</p>
</section>
<section id="row-standardized-weight-matrix" class="level4">
<h4 class="anchored" data-anchor-id="row-standardized-weight-matrix">Row-Standardized Weight Matrix</h4>
<p>Row-standardizing the IDW calculated above:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>rswm_ids <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(knn, <span class="at">glist=</span>ids, <span class="at">style=</span><span class="st">"B"</span>, <span class="at">zero.policy=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">unlist</span>(rswm_ids<span class="sc">$</span>weights))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
0.005361 0.019837 0.029908 0.038547 0.045405 0.374706 </code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="computing-spatially-lagged-values-of-lgas" class="level2">
<h2 class="anchored" data-anchor-id="computing-spatially-lagged-values-of-lgas">Computing Spatially Lagged Values of LGAs</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>Functional_pct.lag <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(rswm_ids, </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                                wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Functional %</span><span class="st">`</span>, </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>Functional_pct.lag</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 0.226351540 0.240110419 0.000000000 0.131074498 0.160787182 0.086379247
  [7] 0.082031398 0.079420704 0.125610669 0.124988303 0.163301623 0.116404180
 [13] 0.101344432 0.077846921 0.164660793 0.153308414 0.137241129 0.134548287
 [19] 0.127356837 0.101505285 0.053695965 0.623596103 0.122156717 0.078294350
 [25] 0.158476496 0.242983817 0.174130273 0.149818347 0.175784974 0.146250913
 [31] 0.087005723 0.692956210 0.232891102 0.042167282 0.203860724 0.092631725
 [37] 0.125527102 0.147535133 0.156680740 0.136268666 0.138613731 0.072374004
 [43] 0.144061619 0.173937306 0.128488777 0.107391491 0.253384290 0.123068318
 [49] 0.488755419 0.053609716 0.427829145 0.144153855 0.088721201 0.102235683
 [55] 0.203046064 0.100758581 0.154847219 0.136487255 0.086135418 0.060184544
 [61] 0.051607813 0.886205895 0.081668242 0.081155645 0.120478954 0.086458460
 [67] 0.160358585 0.228055603 0.071563529 0.155144638 0.220320671 0.083142138
 [73] 0.081740172 0.107479548 0.245773259 0.047236685 0.081457428 0.114937990
 [79] 0.141167614 0.074860525 0.175349737 0.104840976 0.143649719 0.040516415
 [85] 0.272585744 0.070374447 0.171431705 0.100545462 0.149665669 0.046599916
 [91] 0.004569980 0.074552295 0.039784946 0.055300825 0.088679016 0.204143912
 [97] 0.143629969 0.085841592 0.180357361 0.121028501 0.222485562 0.077979698
[103] 0.091191379 0.085142879 0.267061685 0.103701928 0.111758169 0.208520834
[109] 0.123405728 0.179864441 0.160549187 0.050816995 0.109077872 0.128938272
[115] 0.082940901 0.170452794 0.110777772 0.052830640 0.062991899 0.192786081
[121] 0.101259902 0.221231568 0.043691056 0.253738410 0.106902421 0.069792139
[127] 0.177919265 0.087162898 0.110376543 0.282301426 0.081403151 0.087562043
[133] 0.064860389 0.067184443 0.123393350 0.082959387 0.119947899 0.123025983
[139] 0.210869402 0.086735237 0.093684151 1.124637971 0.056221269 0.124082939
[145] 0.241654856 0.067707759 0.169381389 0.062093673 0.175236829 0.149188800
[151] 0.164360934 0.089345555 0.107091813 0.231131830 0.292996590 0.325634453
[157] 0.252933177 0.057490119 0.153929740 0.005297562 0.109434192 0.052578222
[163] 0.045487601 0.069215872 0.162599554 0.194113765 0.185932588 0.206263883
[169] 0.146462491 0.108279185 0.101521737 0.276451837 0.252173978 0.085247578
[175] 0.196529600 0.074461018 0.077273162 0.237833000 0.295471728 0.136216398
[181] 0.139139294 0.190427597 0.067193146 0.166207151 0.115823491 0.118494412
[187] 0.140419668 0.144073207 0.128088033 0.331802259 0.223386315 0.159120636
[193] 0.146539823 0.201056627 0.266003112 0.127558929 0.124270983 0.095017610
[199] 0.093733409 0.096212897 0.067980970 0.177975364 0.140846770 0.167342462
[205] 0.111713603 0.105282914 0.228741716 0.119979093 0.182117879 0.104550215
[211] 0.102570925 0.096676062 0.048358213 0.104362379 0.079941496 0.137595530
[217] 0.111646747 0.131566885 1.076571229 0.066179202 0.142696859 0.091500124
[223] 0.127036502 0.077915093 0.101937418 0.177832722 0.222442558 0.073820119
[229] 0.215374519 0.118420511 0.088222068 0.071377728 0.193743643 0.224713370
[235] 0.287166304 0.042227519 0.043379950 0.237087551 0.118486919 0.078608358
[241] 0.062737234 0.333026749 0.155476311 0.153462174 0.101965830 0.351095554
[247] 0.090341754 0.111969693 0.108411734 0.025825365 0.063814144 0.066442572
[253] 0.078598798 0.084655645 0.219883808 0.081703364 0.138138259 0.153246634
[259] 0.137092957 0.160625576 0.007767122 0.126111077 0.128376773 0.959479547
[265] 0.117977553 0.150540254 0.228820791 0.072385415 0.074651863 0.225591068
[271] 0.036188593 0.295453975 0.118894592 0.084405991 0.540421083 0.521854553
[277] 0.572669144 0.480703051 0.470080301 0.070801022 0.083964080 0.088716334
[283] 0.071034181 0.111054428 0.140896374 0.202944788 0.048988045 0.142417529
[289] 0.084938597 0.092047012 0.151557669 0.214498898 0.185871315 0.132926304
[295] 0.169456817 0.139007041 0.511498094 0.197895691 0.164703191 0.141219795
[301] 0.118477035 0.154289549 0.150457338 0.099844607 0.275813929 0.221984779
[307] 0.102493175 0.059367143 0.114102369 0.100974576 0.111128756 0.113024468
[313] 0.131844980 0.177019753 0.082784854 0.105809392 0.105974033 0.108227118
[319] 0.135881310 0.089526694 0.139134649 0.102208104 0.152964238 0.167307848
[325] 0.166898078 0.735477627 0.113856065 0.178177564 0.108935016 0.059520277
[331] 0.166876543 0.227971076 0.131145220 0.172900818 0.124829430 0.173273178
[337] 0.124458782 0.107035070 0.172651056 0.061713918 0.121492942 0.146236425
[343] 0.243047053 0.240520910 0.099263938 0.121258108 0.157071964 0.179632596
[349] 0.067382453 0.215273405 0.101643485 0.084849558 0.076282771 0.070623547
[355] 0.142420797 0.322640914 0.144659291 0.155719592 0.105397055 0.160433813
[361] 0.087409148 0.130805467 0.088651619 0.103020595 0.112964526 0.171937315
[367] 0.102214762 0.100314822 0.129621968 0.112789728 0.123802631 0.182576639
[373] 0.159366746 0.079247498 0.154244095 0.095511716 0.060584685 0.178736418
[379] 0.090451381 0.098660120 0.092791889 0.205174171 0.115959331 0.116881838
[385] 0.181303221 0.111335542 0.109331277 0.097306214 0.139148568 0.089933610
[391] 0.085832602 0.087267518 0.078638157 0.296807591 0.070117513 0.215072446
[397] 0.117099072 0.188901713 0.181671325 0.062538111 0.096634454 0.048645539
[403] 0.136687216 0.083842069 0.094299992 0.000000000 0.111386894 0.109657539
[409] 0.071526346 0.167564825 0.104126403 0.233482937 1.062834375 0.148551026
[415] 0.228638769 0.060066511 0.109182191 0.125440141 0.114208702 0.181787392
[421] 0.054115979 0.216164301 0.090248112 0.116592253 0.083919483 0.250571565
[427] 0.083594797 0.086905995 0.097791994 0.193788286 0.231929628 0.063036773
[433] 0.204372021 0.211117664 0.185876573 0.078483301 0.068668142 0.104486819
[439] 0.178822895 0.058761631 0.075187753 0.054730233 0.553391506 0.112556392
[445] 0.187993564 0.099885834 0.000000000 0.644991874 0.247805835 0.365581589
[451] 0.184208555 0.038895645 0.222270383 0.112946727 0.081299664 0.054084799
[457] 0.252070267 0.145301150 0.079798883 0.202869013 0.570851694 0.811714758
[463] 0.150375606 0.068629259 0.065638151 0.090773685 0.107401582 0.083063162
[469] 0.100538889 0.060455552 0.065945094 0.135202105 0.057926587 0.344616244
[475] 0.035630259 0.065482640 0.038017756 0.144684260 0.088988413 0.189927038
[481] 0.061766816 0.095870607 0.243568611 0.065364994 0.241070537 0.191633876
[487] 0.067187426 0.191533954 0.121388061 0.057307798 0.160903076 0.000000000
[493] 0.067684336 0.057840673 0.147913156 0.205630329 0.113949071 0.150396956
[499] 0.138431633 0.047855485 0.213140701 0.065834506 0.286375164 0.123303067
[505] 0.151293813 0.139481752 0.017977215 0.085768511 0.005869363 0.087961494
[511] 0.089593122 0.083832757 0.082366891 0.199984242 0.845225611 0.073220092
[517] 0.078187897 0.125663962 0.762976911 0.060347806 0.105460195 0.079044191
[523] 0.104576875 0.100048737 0.004320455 0.029632013 0.082866661 0.114586784
[529] 0.145547863 0.107057570 0.214362058 0.197672125 0.157205178 0.217442897
[535] 0.202005841 0.097384244 0.146707717 0.174215810 0.200195452 0.185014910
[541] 0.109031204 0.152225377 0.243101736 0.080626824 0.052966503 0.098389179
[547] 0.093037349 0.134103315 0.291811477 0.185139083 0.118301467 0.177466014
[553] 0.083999002 0.067568678 0.114156208 0.074044084 0.198444923 0.105716603
[559] 0.084623192 0.261701246 0.069459643 0.125230661 0.089668923 0.086502086
[565] 0.120953554 0.212336923 0.250366079 0.176383224 0.072726152 0.124103157
[571] 0.349053870 0.060175141 0.095035426 0.089870540 0.118994916 0.132142169
[577] 0.083241885 0.078644687 0.079038085 0.213048643 0.075859072 0.112570854
[583] 0.111831861 0.113703097 0.115020318 0.077981437 0.176075674 0.141499998
[589] 0.081252340 0.357778213 0.212327161 0.083030895 0.293625606 0.078993072
[595] 0.187498450 0.056737598 0.129128320 0.205333776 0.124722264 0.082960338
[601] 0.135375772 0.207627252 0.117719150 0.165546140 0.143244223 0.126639090
[607] 0.079387528 0.089101277 0.123091503 0.168589356 0.188809340 0.282445212
[613] 0.143992405 0.133095159 0.152171144 0.136537827 0.126756724 0.110115597
[619] 0.082120287 0.091468444 0.102995232 0.129741349 0.755158940 0.188624755
[625] 0.263915638 0.080651874 0.110265003 0.081644441 0.086373631 0.098511369
[631] 0.184377848 0.189867953 0.201344356 0.109784672 0.118261049 0.186441261
[637] 0.210072420 0.149746945 0.101673848 0.249188714 0.106562537 0.091698496
[643] 0.143255562 0.065708286 0.335017227 0.118203515 0.058599891 0.112597526
[649] 0.062029206 0.230350960 0.102106171 0.076937905 0.207130708 0.364777685
[655] 0.204432123 0.086405536 0.178960533 0.262931016 0.159554823 0.091127491
[661] 0.146804175 0.153317498 0.241955149 0.080786702 0.061858232 0.059797478
[667] 0.220238995 0.102447541 0.103566768 0.033599820 0.146653825 0.096976310
[673] 0.078988598 0.119946882 0.236658458 0.137113610 0.062635517 0.121023619
[679] 0.174823412 0.067095206 0.098850548 0.823659753 0.126075660 0.121218302
[685] 0.305976978 0.323908395 0.104051822 0.054690435 0.173231886 0.164497856
[691] 0.161900414 0.075567196 0.814036580 0.169727171 0.141228106 0.122161041
[697] 0.384447336 0.206822973 0.062980159 0.109124799 0.103115423 0.092881178
[703] 0.785229351 0.068981830 0.071528963 0.194527856 0.397622051 0.072787323
[709] 0.056822359 0.052377516 0.152258188 0.233700187 0.169656070 0.110473969
[715] 0.108494228 0.117012049 0.130541583 0.197323418 0.117919413 0.124370323
[721] 0.245855891 0.069839307 0.131399287 0.058275770 0.161547943 0.237686317
[727] 0.122908404 0.101188829 0.108207418 0.135202916 0.925948397 0.194473307
[733] 0.152898514 0.181561138 0.067039184 0.058762538 0.165869714 0.169064177
[739] 0.059584094 0.066867409 0.219948298 0.088322306 0.277853647 0.141996203
[745] 0.061183594 0.097419599 0.078345399 0.088480401 0.043442763 0.250713885
[751] 0.049324798 0.148168035 0.086053816 0.146475166 0.091976176 0.071615277
[757] 0.083635555 0.084885545 0.112673807 0.231728153 0.091382732 0.215950998
[763] 0.186939472 0.212302004 0.121361916 0.047297891 0.115466229 0.147084355
[769] 0.169588774 0.083820304 0.134700199 0.119586877 0.119829216 0.087179528</code></pre>
</div>
</div>
</section>
<section id="cluster-and-outlier-analysis" class="level2">
<h2 class="anchored" data-anchor-id="cluster-and-outlier-analysis">Cluster and Outlier Analysis</h2>
<section id="global-spatial-autocorrelation-morans-i-test" class="level3">
<h3 class="anchored" data-anchor-id="global-spatial-autocorrelation-morans-i-test">Global Spatial Autocorrelation: Moran’s I test</h3>
<section id="functional-water-points-proportion" class="level4">
<h4 class="anchored" data-anchor-id="functional-water-points-proportion">Functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Functional %</span><span class="st">`</span>, </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">listw =</span> rswm_ids, </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">na.action =</span> na.omit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  wp_nigeria$`Functional %`  
weights: rswm_ids    

Moran I statistic standard deviate = 23.953, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     0.5468788042     -0.0012936611      0.0005237526 </code></pre>
</div>
</div>
<p>The positive Moran’s I value of 0.5469 and low p-value of &lt; 0.05 suggest that there is clustering and significant positive spatial autocorrelation of the proportion of functional water points among the LGAs, and the null hypothesis of spatial randomness is rejected.</p>
</section>
<section id="non-functional-water-points-proportion" class="level4">
<h4 class="anchored" data-anchor-id="non-functional-water-points-proportion">Non-functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Non-functional %</span><span class="st">`</span>, </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">listw =</span> rswm_ids, </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">na.action =</span> na.omit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  wp_nigeria$`Non-functional %`  
weights: rswm_ids    

Moran I statistic standard deviate = 21.878, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     0.4993422521     -0.0012936611      0.0005236328 </code></pre>
</div>
</div>
<p>The positive Moran’s I value of 0.4993 and low p-value of &lt; 0.05 suggest that there is also clustering and significant positive spatial autocorrelation of the proportion of non-functional water points among the LGAs, and the null hypothesis of spatial randomness is rejected.</p>
</section>
</section>
<section id="computing-local-morans-i" class="level3">
<h3 class="anchored" data-anchor-id="computing-local-morans-i">Computing Local Moran’s I</h3>
<section id="functional-water-points-proportion-1" class="level4">
<h4 class="anchored" data-anchor-id="functional-water-points-proportion-1">Functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>localMI_F <span class="ot">&lt;-</span> <span class="fu">localmoran</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Functional %</span><span class="st">`</span>, rswm_ids)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(localMI_F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Ii          E.Ii       Var.Ii       Z.Ii Pr(z != E(Ii))
1  0.21554578 -1.238829e-04 0.0129199587  1.8973982   5.777540e-02
2  0.22281356 -1.382503e-04 0.0148016090  1.8325530   6.686907e-02
3  0.37351463 -4.832013e-04 0.0044596855  5.6003731   2.138909e-08
4 -0.02861668 -4.532287e-05 0.0012540038 -0.8068289   4.197650e-01
5  0.01382552 -3.338868e-06 0.0001326245  1.2008104   2.298247e-01
6  0.11793602 -1.270540e-04 0.0034665893  2.0052240   4.493911e-02</code></pre>
</div>
</div>
</section>
<section id="non-functional-water-points-proportion-1" class="level4">
<h4 class="anchored" data-anchor-id="non-functional-water-points-proportion-1">Non-functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>localMI_NF <span class="ot">&lt;-</span> <span class="fu">localmoran</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Non-functional %</span><span class="st">`</span>, rswm_ids)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(localMI_NF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Ii          E.Ii      Var.Ii      Z.Ii Pr(z != E(Ii))
1 0.45805563 -0.0006328300 0.065953881 1.7860665   7.408849e-02
2 0.43323468 -0.0004045203 0.043294562 2.0840679   3.715399e-02
3 0.25714660 -0.0003326605 0.003075557 4.6428040   3.437123e-06
4 0.03253048 -0.0003751605 0.010364982 0.3232109   7.465355e-01
5 0.36545983 -0.0003111278 0.012349083 3.2914848   9.966000e-04
6 0.16727469 -0.0002513320 0.006854254 2.0234953   4.302211e-02</code></pre>
</div>
</div>
</section>
<section id="appending-local-morans-i-to-nigeria-spatial-polygon-dataframe" class="level4">
<h4 class="anchored" data-anchor-id="appending-local-morans-i-to-nigeria-spatial-polygon-dataframe">Appending Local Moran’s I to Nigeria Spatial Polygon DataFrame</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>wp_nigeria.localMI_F <span class="ot">&lt;-</span> <span class="fu">cbind</span>(wp_nigeria, localMI_F) <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Pr.Ii =</span> Pr.z....E.Ii..)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>wp_nigeria.localMI_NF <span class="ot">&lt;-</span> <span class="fu">cbind</span>(wp_nigeria, localMI_NF) <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Pr.Ii =</span> Pr.z....E.Ii..)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mapping-local-morans-i-values-and-p-values" class="level4">
<h4 class="anchored" data-anchor-id="mapping-local-morans-i-values-and-p-values">Mapping Local Moran’s I values and p-values</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>localMI_F.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(wp_nigeria.localMI_F) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Ii"</span>, </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"RdBu"</span>, </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Local Moran's I"</span>) <span class="sc">+</span> </span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Local Moran's I statistics (Functional)"</span>, </span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>,</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>pvalue_F.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(wp_nigeria.localMI_F) <span class="sc">+</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Pr.Ii"</span>, </span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="cn">Inf</span>),</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-Blues"</span>, </span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"P-values"</span>) <span class="sc">+</span> </span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Local Moran's I p-values (Functional)"</span>, </span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>,</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>localMI_NF.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(wp_nigeria.localMI_NF) <span class="sc">+</span></span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Ii"</span>, </span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>,</span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"-RdBu"</span>, </span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Local Moran's I"</span>) <span class="sc">+</span> </span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Local Moran's I statistics (Non-functional)"</span>, </span>
<span id="cb41-27"><a href="#cb41-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.0</span>,</span>
<span id="cb41-28"><a href="#cb41-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb41-29"><a href="#cb41-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb41-30"><a href="#cb41-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-31"><a href="#cb41-31" aria-hidden="true" tabindex="-1"></a>pvalue_NF.map <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(wp_nigeria.localMI_NF) <span class="sc">+</span></span>
<span id="cb41-32"><a href="#cb41-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Pr.Ii"</span>, </span>
<span id="cb41-33"><a href="#cb41-33" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="cn">Inf</span>),</span>
<span id="cb41-34"><a href="#cb41-34" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-Oranges"</span>, </span>
<span id="cb41-35"><a href="#cb41-35" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"P-values"</span>) <span class="sc">+</span> </span>
<span id="cb41-36"><a href="#cb41-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Local Moran's I p-values (Non-functional)"</span>, </span>
<span id="cb41-37"><a href="#cb41-37" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.0</span>,</span>
<span id="cb41-38"><a href="#cb41-38" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.outside =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb41-39"><a href="#cb41-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb41-40"><a href="#cb41-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-41"><a href="#cb41-41" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(localMI_F.map, pvalue_F.map, localMI_NF.map, pvalue_NF.map, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Variable(s) "Ii" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Legend labels were too wide. The labels have been resized to 0.53, 0.59, 0.59, 0.59, 0.61. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Variable(s) "Ii" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Legend labels were too wide. The labels have been resized to 0.53, 0.59, 0.59, 0.59, 0.61. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="take-home_ex1_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Local Moran’s I and p-value maps show that there is statistically significant clustering of high proportion of functional water points in the northern regions of Nigeria. In the southern region, there is also statistical significance of spatial autocorrelation of non-functional water point presence.</p>
</section>
</section>
</section>
<section id="creating-lisa-cluster-map" class="level2">
<h2 class="anchored" data-anchor-id="creating-lisa-cluster-map">Creating LISA Cluster Map</h2>
<section id="plotting-moran-scatterplot" class="level3">
<h3 class="anchored" data-anchor-id="plotting-moran-scatterplot">Plotting Moran Scatterplot</h3>
<section id="functional-water-points-proportion-2" class="level4">
<h4 class="anchored" data-anchor-id="functional-water-points-proportion-2">Functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>nci_F <span class="ot">&lt;-</span> <span class="fu">moran.plot</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Functional %</span><span class="st">`</span>, rswm_ids,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">labels =</span> <span class="fu">as.character</span>(wp_nigeria<span class="sc">$</span>shapeName), </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">xlab=</span><span class="st">"% Functional"</span>, </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ylab=</span><span class="st">"Spatially Lag % Functional"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="take-home_ex1_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="non-functional-water-points-proportion-2" class="level4">
<h4 class="anchored" data-anchor-id="non-functional-water-points-proportion-2">Non-functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>nci_NF <span class="ot">&lt;-</span> <span class="fu">moran.plot</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Non-functional %</span><span class="st">`</span>, rswm_ids,</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">labels =</span> <span class="fu">as.character</span>(wp_nigeria<span class="sc">$</span>shapeName), </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">xlab=</span><span class="st">"% Non-functional"</span>, </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ylab=</span><span class="st">"Spatially Lag % Non-functional"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="take-home_ex1_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="plotting-moran-scatterplot-with-standardized-variable" class="level3">
<h3 class="anchored" data-anchor-id="plotting-moran-scatterplot-with-standardized-variable">Plotting Moran Scatterplot with Standardized Variable</h3>
<section id="functional-water-points-proportion-3" class="level4">
<h4 class="anchored" data-anchor-id="functional-water-points-proportion-3">Functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Z.Functional %</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">scale</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Functional %</span><span class="st">`</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  as.vector </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>nci_F2 <span class="ot">&lt;-</span> <span class="fu">moran.plot</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Functional %</span><span class="st">`</span>, rswm_ids,</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">labels =</span> <span class="fu">as.character</span>(wp_nigeria<span class="sc">$</span>shapeName),</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xlab =</span> <span class="st">"z-% Functional"</span>, </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ylab=</span><span class="st">"Spatially Lag z-% Functional"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="take-home_ex1_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="non-functional-water-points-proportion-3" class="level4">
<h4 class="anchored" data-anchor-id="non-functional-water-points-proportion-3">Non-functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Z.Non-functional %</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">scale</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Non-functional %</span><span class="st">`</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  as.vector </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>nci_NF2 <span class="ot">&lt;-</span> <span class="fu">moran.plot</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Non-functional %</span><span class="st">`</span>, rswm_ids,</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">labels =</span> <span class="fu">as.character</span>(wp_nigeria<span class="sc">$</span>shapeName),</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">xlab =</span> <span class="st">"z-% Non-functional"</span>, </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ylab=</span><span class="st">"Spatially Lag z-% Non-functional"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="take-home_ex1_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="preparing-lisa-map-classes" class="level3">
<h3 class="anchored" data-anchor-id="preparing-lisa-map-classes">Preparing LISA Map Classes</h3>
<section id="functional-water-points-proportion-4" class="level4">
<h4 class="anchored" data-anchor-id="functional-water-points-proportion-4">Functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>quadrant_F <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">mode =</span> <span class="st">"numeric"</span>, <span class="at">length =</span> <span class="fu">nrow</span>(localMI_F))</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">lag_Functional %</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(rswm_ids, wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Functional %</span><span class="st">`</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>DV_F <span class="ot">&lt;-</span> wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">lag_Functional %</span><span class="st">`</span> <span class="sc">-</span> <span class="fu">mean</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">lag_Functional %</span><span class="st">`</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>LM_I_F <span class="ot">&lt;-</span> localMI_F[,<span class="dv">1</span>]   </span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>signif <span class="ot">&lt;-</span> <span class="fl">0.05</span>       </span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>quadrant_F[DV_F <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> LM_I_F <span class="sc">&gt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>quadrant_F[DV_F <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> LM_I_F <span class="sc">&lt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>quadrant_F[DV_F <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> LM_I_F <span class="sc">&lt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">3</span>  </span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>quadrant_F[DV_F <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> LM_I_F <span class="sc">&gt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">4</span>    </span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>quadrant_F[localMI_F[,<span class="dv">5</span>] <span class="sc">&gt;</span> signif] <span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="non-functional-water-points-proportion-4" class="level4">
<h4 class="anchored" data-anchor-id="non-functional-water-points-proportion-4">Non-functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>quadrant_NF <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">mode =</span> <span class="st">"numeric"</span>, <span class="at">length =</span> <span class="fu">nrow</span>(localMI_NF))</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">lag_Non-functional %</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(rswm_ids, wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Non-functional %</span><span class="st">`</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>DV_NF <span class="ot">&lt;-</span> wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">lag_Non-functional %</span><span class="st">`</span> <span class="sc">-</span> <span class="fu">mean</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">lag_Non-functional %</span><span class="st">`</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>LM_I_NF <span class="ot">&lt;-</span> localMI_NF[,<span class="dv">1</span>]   </span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>signif <span class="ot">&lt;-</span> <span class="fl">0.05</span>       </span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>quadrant_NF[DV_NF <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> LM_I_NF <span class="sc">&gt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>quadrant_NF[DV_NF <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> LM_I_NF <span class="sc">&lt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>quadrant_NF[DV_NF <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> LM_I_NF <span class="sc">&lt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">3</span>  </span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>quadrant_NF[DV_NF <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> LM_I_NF <span class="sc">&gt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">4</span>    </span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>quadrant_NF[localMI_NF[,<span class="dv">5</span>] <span class="sc">&gt;</span> signif] <span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="plotting-lisa-map" class="level3">
<h3 class="anchored" data-anchor-id="plotting-lisa-map">Plotting LISA Map</h3>
<section id="functional-water-points-proportion-5" class="level4">
<h4 class="anchored" data-anchor-id="functional-water-points-proportion-5">Functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>pct_functional <span class="ot">&lt;-</span> <span class="fu">qtm</span>(wp_nigeria, <span class="st">"Functional %"</span>, <span class="at">fill.palette =</span> <span class="st">"Blues"</span>) <span class="sc">+</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"% Functional Water Points"</span>, </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.format =</span> <span class="fu">list</span>(<span class="at">fun=</span><span class="cf">function</span>(x) <span class="fu">paste0</span>(<span class="fu">formatC</span>(x <span class="sc">*</span> <span class="dv">100</span>, <span class="at">digits=</span><span class="dv">0</span>, <span class="at">format=</span><span class="st">"f"</span>), <span class="st">" %"</span>)))</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>wp_nigeria.localMI_F<span class="sc">$</span>quadrant <span class="ot">&lt;-</span> quadrant_F</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>colors_F <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#ffffff"</span>, <span class="st">"#d7191c"</span>, <span class="st">"#fdae61"</span>, <span class="st">"#abd9e9"</span>, <span class="st">"#2c7bb6"</span>)</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>clusters <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"insignificant"</span>, <span class="st">"low-low"</span>, <span class="st">"low-high"</span>, <span class="st">"high-low"</span>, <span class="st">"high-high"</span>)</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>LISAmap_F <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(wp_nigeria.localMI_F) <span class="sc">+</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"quadrant"</span>, </span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"cat"</span>, </span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> colors_F[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant_F))) <span class="sc">+</span> <span class="dv">1</span>], </span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>          <span class="at">labels =</span> clusters[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant_F))) <span class="sc">+</span> <span class="dv">1</span>],</span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">popup.vars =</span> <span class="fu">c</span>(<span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">17</span>)) <span class="sc">+</span></span>
<span id="cb54-17"><a href="#cb54-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb54-18"><a href="#cb54-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"LISA Map"</span>, </span>
<span id="cb54-19"><a href="#cb54-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>)</span>
<span id="cb54-20"><a href="#cb54-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-21"><a href="#cb54-21" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(pct_functional, LISAmap_F, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="take-home_ex1_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The LISA map reveals a statistically significant cluster of LGAs with high proportion of functional water points in the northern region.</p>
</section>
<section id="non-functional-water-points-proportion-5" class="level4">
<h4 class="anchored" data-anchor-id="non-functional-water-points-proportion-5">Non-functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>pct_nonfunctional <span class="ot">&lt;-</span> <span class="fu">qtm</span>(wp_nigeria, <span class="st">"Non-functional %"</span>, <span class="at">fill.palette =</span> <span class="st">"Oranges"</span>) <span class="sc">+</span> </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"% Non-functional Water Points"</span>, </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>,</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.format =</span> <span class="fu">list</span>(<span class="at">fun=</span><span class="cf">function</span>(x) <span class="fu">paste0</span>(<span class="fu">formatC</span>(x <span class="sc">*</span> <span class="dv">100</span>, <span class="at">digits=</span><span class="dv">0</span>, <span class="at">format=</span><span class="st">"f"</span>), <span class="st">" %"</span>)))</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>wp_nigeria.localMI_NF<span class="sc">$</span>quadrant <span class="ot">&lt;-</span> quadrant_NF</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>colors_NF <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#ffffff"</span>, <span class="st">"#2c7bb6"</span>, <span class="st">"#abd9e9"</span>, <span class="st">"#fdae61"</span>, <span class="st">"#d7191c"</span>)</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>clusters <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"insignificant"</span>, <span class="st">"low-low"</span>, <span class="st">"low-high"</span>, <span class="st">"high-low"</span>, <span class="st">"high-high"</span>)</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>LISAmap_NF <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(wp_nigeria.localMI_NF) <span class="sc">+</span></span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"quadrant"</span>, </span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"cat"</span>, </span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> colors_NF[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant_NF))) <span class="sc">+</span> <span class="dv">1</span>], </span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>          <span class="at">labels =</span> clusters[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant_NF))) <span class="sc">+</span> <span class="dv">1</span>],</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">popup.vars =</span> <span class="fu">c</span>(<span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">17</span>)) <span class="sc">+</span></span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"LISA Map"</span>, </span>
<span id="cb55-19"><a href="#cb55-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>)</span>
<span id="cb55-20"><a href="#cb55-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-21"><a href="#cb55-21" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(pct_nonfunctional, LISAmap_NF, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="take-home_ex1_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The LISA map reveals a statistically significant cluster of LGAs with high proportion of non-functional water points in the southwestern region.</p>
<p>The northeastern region appears as low-low quadrant in both functional and non-functional maps, indicating that this region has a low count of water points overall.</p>
</section>
</section>
</section>
<section id="hot-spot-and-cold-spot-area-analysis" class="level2">
<h2 class="anchored" data-anchor-id="hot-spot-and-cold-spot-area-analysis">Hot Spot and Cold Spot Area Analysis</h2>
<section id="computing-adaptive-distance-weight-matrix-1" class="level3">
<h3 class="anchored" data-anchor-id="computing-adaptive-distance-weight-matrix-1">Computing Adaptive Distance Weight Matrix</h3>
<p>Continuing from the <em>knn</em> variable derived earlier above, we convert the nb object into a spatial weights object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>knn_lw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(knn, <span class="at">style =</span> <span class="st">'B'</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(knn_lw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 774 
Number of nonzero links: 6192 
Percentage nonzero weights: 1.033592 
Average number of links: 8 
Non-symmetric neighbours list
Link number distribution:

  8 
774 
774 least connected regions:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 with 8 links
774 most connected regions:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 with 8 links

Weights style: B 
Weights constants summary:
    n     nn   S0    S1     S2
B 774 599076 6192 11152 201938</code></pre>
</div>
</div>
</section>
<section id="computing-gi-statistics" class="level3">
<h3 class="anchored" data-anchor-id="computing-gi-statistics">Computing Gi Statistics</h3>
<section id="functional-water-points-proportion-6" class="level4">
<h4 class="anchored" data-anchor-id="functional-water-points-proportion-6">Functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>gi_F <span class="ot">&lt;-</span> <span class="fu">localG</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Functional %</span><span class="st">`</span>, knn_lw)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>wp_nigeria.gi_F <span class="ot">&lt;-</span> <span class="fu">cbind</span>(wp_nigeria, <span class="fu">as.matrix</span>(gi_F)) <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">gstat_F =</span> as.matrix.gi_F.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="non-functional-water-points-proportion-6" class="level4">
<h4 class="anchored" data-anchor-id="non-functional-water-points-proportion-6">Non-functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>gi_NF <span class="ot">&lt;-</span> <span class="fu">localG</span>(wp_nigeria<span class="sc">$</span><span class="st">`</span><span class="at">Non-functional %</span><span class="st">`</span>, knn_lw)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>wp_nigeria.gi_NF <span class="ot">&lt;-</span> <span class="fu">cbind</span>(wp_nigeria, <span class="fu">as.matrix</span>(gi_NF)) <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">gstat_NF =</span> as.matrix.gi_NF.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="mapping-gi-values-with-adaptive-distance-weights" class="level3">
<h3 class="anchored" data-anchor-id="mapping-gi-values-with-adaptive-distance-weights">Mapping Gi Values with Adaptive Distance Weights</h3>
<section id="functional-water-points-proportion-7" class="level4">
<h4 class="anchored" data-anchor-id="functional-water-points-proportion-7">Functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>Gimap_F <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(wp_nigeria.gi_F) <span class="sc">+</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"gstat_F"</span>, </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>, </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"RdBu"</span>, </span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Local Gi"</span>) <span class="sc">+</span> </span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Local Gi"</span>, </span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>)</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(pct_functional, </span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>             Gimap_F, </span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Variable(s) "gstat_F" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="take-home_ex1_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The local Gi map reveals the hot spot area for high proportion of functional water points in the northern region, in line with the earlier maps’ revelation. The cold spot areas appear in the southern and northeastern regions, indicating a clustering of low proportion of functional water points in those areas.</p>
</section>
<section id="non-functional-water-points-proportion-7" class="level4">
<h4 class="anchored" data-anchor-id="non-functional-water-points-proportion-7">Non-functional Water Points Proportion</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>Gimap_NF <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(wp_nigeria.gi_NF) <span class="sc">+</span> </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"gstat_NF"</span>, </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>, </span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-RdBu"</span>, </span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Local Gi"</span>) <span class="sc">+</span> </span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Local Gi"</span>, </span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.1</span>)</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(pct_nonfunctional, </span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>             Gimap_NF, </span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Variable(s) "gstat_NF" contains positive and negative values, so midpoint is set to 0. Set midpoint = NA to show the full spectrum of the color palette.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="take-home_ex1_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The local Gi map reveals the hot spot area for high proportion of non-functional water points in the southwestern region, in line with the earlier maps’ revelation.</p>
<p>The cold spot area appears in the northeastern region, which was also the cold spot area for functional water points. This indicates that the area is a clustering of low counts of water points overall.</p>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>